allowedDeprecatedVersions:

ignoredBuiltDependencies:

minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - "@biomejs/biome"
  - "@biomejs/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - prisma
