import type { HTMLNode } from "./HTMLNode";

/**
 * Formats an HTMLNode[] tree into XML-style document with indentation.  The
 * HTML is formatted with 2-space indentation.  The HTML is escaped to prevent
 * XSS attacks.
 *
 * @param html - The HTML to format.
 * @returns The formatted HTML as a string.
 */
export default function formatHTMLTree(html: HTMLNode[]): string {
  function formatNode(node: HTMLNode, indent = 0): string {
    const pad = "  ".repeat(indent);

    if (node.type === "text") {
      // Escape XML special chars
      const escaped = node.content
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      return pad + escaped;
    } else {
      const attrs = node.attributes
        ? Object.entries(node.attributes)
            .sort(([a], [b]) => a.localeCompare(b))
            // Remove id attributes that are generated by the form library
            .filter(
              ([key, value]) =>
                !((key === "id" || key === "for") && value.match(/^_r_\d+_$/)),
            )
            .map(([key, value]) =>
              value === undefined || value === null || value === ""
                ? key
                : `${key}="${value.replace(/"/g, "&quot;")}"`,
            )
            .join(" ")
        : "";

      const tagStart =
        attrs && attrs.length > 0 ? `<${node.tag} ${attrs}>` : `<${node.tag}>`;
      const tagSelfClose =
        attrs && attrs.length > 0
          ? `<${node.tag} ${attrs} />`
          : `<${node.tag} />`;

      if (!node.children || node.children.length === 0) {
        // Use self-closing for void/self-closing tags
        if (
          /^(area|base|br|col|embed|hr|img|input|link|meta|source|track|wbr)$/i.test(
            node.tag,
          )
        ) {
          return pad + tagSelfClose;
        } else {
          return `${pad + tagStart}</${node.tag}>`;
        }
      }

      const children = node.children
        .map((child) => formatNode(child, indent + 1))
        .join("\n");
      return `${pad + tagStart}\n${children}\n${pad}</${node.tag}>`;
    }
  }

  return html.map((node) => formatNode(node, 0)).join("\n");
}
